version: "3.9"

services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: authpoint
      MINIO_ROOT_PASSWORD: youshallnotpass
    command: server --console-address ":9001" /data

volumes:
  postgresql: { }
  minio_data:
    driver: local