spring:
  application:
    name: authpoint
  datasource:
    url: jdbc:postgresql://authpoint_db:5432/authpoint_db
    username: authpoint_user
    password: authpoint_password
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    validate-on-migrate: true
  config:
    activate:
      on-profile: default

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health

jwt:
  secret: youshallnotpassyoushallnotpassyoushallnotpassyoushallnotpassyoushallnotpassyoushallnotpassyoushallnotpassyoushallnotpass

grpc:
  server:
    port: 9098
    address: 0.0.0.0
    security:
      enabled: false

kafka:
  topics:
    notification:
      destination: notifypoint.notifications
  clusters:
    default:
      bootstrap-servers:
        - tochkaszapyatoi.ru:29092
      properties:
        acks: -1
        delivery.timeout.ms: 90000
        batch.size: 10240
        linger.ms: 100
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true
      producer:
        client-id: tanpii.authpoint
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      security:
        protocol: PLAINTEXT

web-clients:
  clients:
    bookpoint:
      destination: http://tochkaszapyatoi.ru:8081
      headers:
        X-INTERNAL-API: "AUTH_POINT_INTERNAL_KEY"

api:
  management:
    header: "X-MANAGEMENT-API"
    key: "AUTH-POINT"

server:
  error:
    whitelabel:
      enabled: off
  tomcat:
    reject-illegal-header: off
